[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "biosbi"
version = "0.2"
requires-python = ">=3.12"
description = "Interactive cryo-EM and simulation-based inference teaching app, adapted from cryoSBI."
authors = [
    { name = "Sebastian Metzler" },
    { name = "Friedrich Zeddies" }
]
maintainers = [
    { name = "Sebastian Metzler" },
    { name = "Friedrich Zeddies" }
]
dependencies = [
    "lampe",
    "zuko",
    "torch",
    "numpy",
    "matplotlib",
    "scipy",
    "torchvision",
    "mrcfile",
    "trimesh>=4.11.3",
    "rtree>=1.4.1",
    "streamlit>=1.50.0",
    "pygltflib>=1.16.5",
    "seaborn>=0.13.2",
    "umap-learn>=0.5.7",
    "streamlit-stl>=0.0.6",
]

[project.urls]
Repository = "https://github.com/flatironinstitute/cryoSBI"
Source = "https://github.com/flatironinstitute/cryoSBI"

[project.scripts]
train_npe_model = "cryo_sbi.inference.command_line_tools:cl_npe_train_no_saving"
model_to_tensor = "cryo_sbi.utils.command_line_tools:cl_models_to_tensor"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["cryo_sbi*"]
